appName : IAM User Portal
theme : org.wso2.carbon.uuf.common.theme.default
menu :
  main :
    Home : {link: "", icon: "fw-home"}
    Users :
      Login : {link: "login", icon: "fw fw-add"}
      Sign up : {link: "user/signup", icon: "fw fw-add"}
      Reset Password : {link: "user/reset-password", icon: "fw fw-add"}
<<<<<<< HEAD
      User Profile: {link: "profile", icon: "fw fw-user"}
=======
      Account Settings : {link: "users/account/account-setting", icon: "fw fw-add"}
>>>>>>> 2db65e8... Added tab view to the user portal
errorPages:
  "404": /foundation/error/404
  "401": /login
  default: /foundation/error/default
loginPageUri: "/login"
loginRedirectUri: "/"